// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://plbmgjqitlxedsmdqpld.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBsYm1nanFpdGx4ZWRzbWRxcGxkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkxNTIyMjYsImV4cCI6MjA2NDcyODIyNn0.m6MsXWqI6TbJQ1EeaX8R7L7GHzA23ZaffCmKrVdVD_U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    autoRefreshToken: true,
    persistSession: true,
    detectSessionInUrl: true,
    flowType: 'pkce',
    debug: process.env.NODE_ENV === 'development',
    // Enhanced settings for persistent sessions
    storageKey: 'sb-persistent-auth-token',
    // Set very long session duration (30 days)
    refreshThreshold: 30 * 60, // Refresh 30 minutes before expiry
  },
  realtime: {
    params: {
      eventsPerSecond: 5, // Reduced to prevent connection issues
    },
    timeout: 30000, // 30 seconds - reduced timeout
    heartbeatIntervalMs: 15000, // 15 seconds - reduced heartbeat
    reconnectAfterMs: 3000, // 3 seconds - faster reconnection
  },
  global: {
    headers: {
      'X-Client-Info': 'analy-ticket-persistent@1.0.0'
    }
  }
});