name: Test Suite

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Install Playwright browsers
      run: npx playwright install --with-deps
    
    - name: Run ESLint
      run: npm run lint
    
    - name: Run unit tests
      run: npm run test:coverage
    
    - name: Run E2E tests
      run: npm run test:e2e
    
    - name: Run accessibility tests
      run: npm run test:e2e -- --project=chromium --grep @accessibility
    
    - name: Run performance tests
      run: npm run test:e2e -- --project=chromium --grep @performance
    
    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: |
          coverage/
          test-results/
          playwright-report/
        retention-days: 30

  report:
    needs: test
    runs-on: ubuntu-latest
    if: always()

    steps:
    - uses: actions/download-artifact@v4
      with:
        name: test-results
    
    - name: Generate test report
      uses: dorny/test-reporter@v1
      with:
        name: Test Results
        path: 'test-results/*.json'
        reporter: jest-json 